version: "3"
services:
  web:
    build:
      context: ./apache-php
    ports:
      - 80:80
    privileged: true
    links:
      - db
    volumes:
      - "./matching-backend/:/var/www/html"
      - "./apache-php/apache.conf:/etc/httpd/conf/httpd.conf"
    container_name: "web"
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: "mysql8.0"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    container_name: "phpmyamin"
  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
